(()=>{
 const $=id=>document.getElementById(id), sets=window.DAILY_SETS, key='gate-daily-100-v1';
 const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let data;try{data=JSON.parse(localStorage.getItem(key))||{runs:{},days:[]}}catch{data={runs:{},days:[]}};
 let active=null, todayIndex;
 const day=()=>Math.floor((Date.now()+19800000)/86400000);
 const featured=()=>((day()-Math.floor(Date.UTC(2026,8,26)/86400000))%100+100)%100+1;
 function save(){try{localStorage.setItem(key,JSON.stringify(data))}catch{ $('dailyStats').textContent='Browser storage unavailable. Keep this page open to retain progress.';}}
 function stats(){let d=day(),streak=0;if(!data.days.includes(d))d--;while(data.days.includes(d)){streak++;d--;}const done=Object.values(data.runs).filter(r=>r.done),correct=done.reduce((s,r)=>s+r.score,0);$('dailyStreak').textContent=`${streak} ${streak===1?'day':'days'}`;$('dailyStats').innerHTML=`<div><b>${done.length}<small>/100 sets complete</small></b><b>${done.length?Math.round(correct/(done.length*20)*100):0}%<small>answer accuracy</small></b></div>`;}
 function render(){todayIndex=featured();$('featuredTitle').textContent=`Set ${String(todayIndex).padStart(3,'0')} · Mixed CS practice`;$('featuredNumber').textContent=String(todayIndex).padStart(3,'0');$('dailyDate').textContent=new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',day:'numeric',month:'short',year:'numeric'}).format(new Date());stats();grid();}
 function grid(){let mode=$('setFilter').value;const filtered=sets.filter(s=>{let r=data.runs[s.id];return mode==='all'||(mode==='new'&&!r)||(mode==='active'&&r&&!r.done)||(mode==='done'&&r?.done)});$('setsGrid').innerHTML=filtered.map(s=>{const r=data.runs[s.id];return `<button class="set-card ${s.id===todayIndex?'featured':''}" data-set="${s.id}"><div><span>SET ${String(s.id).padStart(3,'0')}</span><span>${r?.done?'✓ Complete':s.id===todayIndex?'Today':r?'In progress':'Ready'}</span></div><h3>${['Build your foundation','Keep the momentum','Sharpen your accuracy','Test your fluency','Make practice count'][(s.id-1)%5]}</h3><p>20 questions · 30 min</p><div class="set-card-bottom"><span>${r?.done?`${r.score}/20 correct`:r?`${Object.keys(r.answers).length}/20 answered`:'Mixed subjects'}</span><b>${r?.done?'Review':r?'Resume':'Practice'} →</b></div></button>`}).join('')||'<p class="muted">No sets in this category yet.</p>';document.querySelectorAll('[data-set]').forEach(b=>b.onclick=()=>open(Number(b.dataset.set)));}
 function open(id){active=id;if(!data.runs[id]){data.runs[id]={index:0,answers:{},review:{},deadline:Date.now()+1800000,done:false};save()}$('dailyExam').classList.remove('hidden');if(!data.runs[id].done&&Date.now()>=data.runs[id].deadline)finish();else exam();$('dailyExam').scrollIntoView({behavior:'smooth',block:'start'});}
 function capture(){if(!active)return;const r=data.runs[active], input=$('dailyAnswer');if(!r.done&&input){const v=input.value.trim();if(v==='')delete r.answers[r.index];else r.answers[r.index]=v;save();}}
 function exam(){const s=sets[active-1],r=data.runs[active];if(r.done)return result();const q=s.questions[r.index];$('dailyExam').innerHTML=`<div class="daily-exam-header"><div><span class="eyebrow">SET ${String(active).padStart(3,'0')} · QUESTION ${r.index+1}/20</span><h2>${escape(q.subject)}</h2></div><div><strong id="dailyClock"></strong><button class="ghost-btn" id="closeDaily">Close</button></div></div><div class="daily-workspace"><article class="question-card"><span class="pill">NAT · 1 mark · No negative marking</span><p class="stem">${escape(q.stem)}</p><label for="dailyAnswer">Your numerical answer</label><div><input id="dailyAnswer" class="nat-input" type="number" step="any" value="${escape(r.answers[r.index]??'')}" placeholder="Enter a number"></div><p class="muted daily-caption">Decimal answers accepted within ±0.001.</p><div class="exam-actions"><button class="ghost-btn" id="dailyPrev" ${r.index===0?'disabled':''}>Previous</button><button class="ghost-btn" id="dailyReview">${r.review[r.index]?'Unmark':'Mark for review'}</button><button class="primary-btn" id="dailyNext">${r.index===19?'Save response':'Save & Next →'}</button></div></article><aside class="card"><h3>Question palette</h3><div class="palette">${s.questions.map((q,i)=>`<button data-daily-q="${i}" aria-label="Question ${i+1}" class="${r.index===i?'is-current ':''}${r.answers[i]!==undefined?'is-answered ':''}${r.review[i]?'is-review':''}">${i+1}</button>`).join('')}</div><p class="daily-caption muted">Green: answered · Yellow: review</p><button class="primary-btn full" id="finishDaily">Submit set</button><p class="muted daily-caption">Answers save as you type. The timer continues when you close or leave.</p></aside></div>`;
 $('dailyAnswer').oninput=capture;$('dailyPrev').onclick=()=>{capture();r.index--;save();exam()};$('dailyNext').onclick=()=>{capture();r.index=Math.min(19,r.index+1);save();exam()};$('dailyReview').onclick=()=>{capture();r.review[r.index]=!r.review[r.index];save();exam()};document.querySelectorAll('[data-daily-q]').forEach(b=>b.onclick=()=>{capture();r.index=Number(b.dataset.dailyQ);save();exam()});$('finishDaily').onclick=()=>{capture();if(confirm(`Submit set? ${Object.keys(r.answers).length}/20 answered.`))finish()};$('closeDaily').onclick=close;tick();}
 function close(){capture();active=null;$('dailyExam').classList.add('hidden');render();}
 function finish(){const r=data.runs[active];if(r.done)return;capture();r.done=true;r.score=sets[active-1].questions.filter((q,i)=>r.answers[i]!==undefined&&Math.abs(Number(r.answers[i])-q.answer)<=.001).length;if(!data.days.includes(day()))data.days.push(day());save();render();result();}
 function result(){const r=data.runs[active],s=sets[active-1];$('dailyExam').innerHTML=`<div class="daily-exam-header"><div><span class="eyebrow">SET ${String(active).padStart(3,'0')} COMPLETE</span><h2>${r.score}/20 correct · ${r.score*5}% accuracy</h2><p>Review the reasoning, then revisit any missed concepts.</p></div><button class="ghost-btn" id="closeDaily">Close review</button></div><div class="solutions">${s.questions.map((q,i)=>{let v=r.answers[i],ok=v!==undefined&&Math.abs(Number(v)-q.answer)<=.001;return `<details class="review-item ${ok?'correct':v===undefined?'unanswered':'wrong'}"><summary>Q${i+1} · ${escape(q.topic)} <b>${ok?'Correct':v===undefined?'Unanswered':'Incorrect'}</b></summary><p>${escape(q.stem)}</p><p>Your answer: <b>${escape(v??'—')}</b> · Correct: <b>${Number(q.answer.toFixed(6))}</b></p><p>${escape(q.explanation)}</p></details>`}).join('')}</div><button class="secondary-btn" id="retryDaily">Retry this set</button>`;$('closeDaily').onclick=close;$('retryDaily').onclick=()=>{if(confirm('Replace this attempt and restart the 30-minute timer?')){delete data.runs[active];save();open(active);render();}};}
 function tick(){let remaining=86400000-((Date.now()+19800000)%86400000);$('nextDaily').textContent=`Next featured set in ${Math.floor(remaining/3600000)}h ${Math.floor(remaining%3600000/60000)}m · midnight IST`;if(todayIndex!==featured())render();if(active&&!data.runs[active].done){let s=Math.max(0,Math.ceil((data.runs[active].deadline-Date.now())/1000));if($('dailyClock'))$('dailyClock').textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;if(s===0)finish();}}
 $('startDaily').onclick=()=>open(featured());$('setFilter').onchange=grid;render();tick();setInterval(tick,1000);window.addEventListener('pagehide',capture);
})();
