// Each set is a reproducible numerical variant, not a claimed new official paper.
window.DAILY_SETS=Array.from({length:100},(_,i)=>{
 const n=i+1, qs=[];
 function q(subject,topic,stem,answer,explanation){qs.push({id:`S${n}Q${qs.length+1}`,subject,topic,stem,answer,explanation,type:'NAT',marks:1,difficulty:'Medium'});}
 let a=n+3,b=n+7;
 q('General Aptitude','Ratios',`Two quantities are in the ratio 3:5 and have sum ${8*a}. Find the smaller quantity.`,3*a,`There are 8 ratio units. One unit is ${8*a}/8 = ${a}; the smaller quantity is 3 × ${a} = ${3*a}.`);
 q('General Aptitude','Work rates',`A worker finishes a job in ${2*a} days; another finishes it in ${6*a} days. Working together at constant rates, how many days do they need?`,1.5*a,`Combined rate = 1/${2*a} + 1/${6*a} = 4/${6*a}. Time = ${6*a}/4 = ${1.5*a} days.`);
 q('Engineering Mathematics','Combinatorics',`A complete undirected simple graph has ${n+4} vertices. How many edges does it have?`,(n+4)*(n+3)/2,`Each pair forms one edge: v(v−1)/2 = ${(n+4)*(n+3)/2}.`);
 q('Engineering Mathematics','Linear algebra',`Find the determinant of the matrix [[${a}, 2], [3, ${b}]].`,a*b-6,`For a 2×2 matrix, det = ad−bc = ${a} × ${b} − 2 × 3 = ${a*b-6}.`);
 q('Engineering Mathematics','Probability',`A box contains ${a} red and ${a} blue balls. Two balls are drawn without replacement. What is the probability both are red? Give a decimal to at least four places.`,a*(a-1)/(2*a*(2*a-1)),`Multiply conditional probabilities: (${a}/${2*a}) × (${a-1}/${2*a-1}) = ${a*(a-1)/(2*a*(2*a-1))}.`);
 q('Digital Logic','Number representation',`What is the decimal value of the unsigned binary number ${(n+16).toString(2)}?`,n+16,`Sum the powers of 2 at the positions containing 1. The result is ${n+16}.`);
 q('Digital Logic','Combinational circuits',`A circuit takes ${n+2} Boolean inputs. How many rows of its truth table have exactly two inputs equal to 1?`,(n+2)*(n+1)/2,`Choose two of ${n+2} input positions: C(${n+2},2) = ${(n+2)*(n+1)/2}.`);
 q('Computer Organization','Pipeline',`An ideal 5-stage pipeline runs ${n+20} instructions. Every stage takes 2 ns and there are no stalls. What is total time in ns, including filling the pipeline?`,(n+24)*2,`Total cycles = stages + instructions − 1 = ${n+24}. Multiply by 2 ns: ${(n+24)*2} ns.`);
 q('Computer Organization','Performance',`A program executes ${n+10} million instructions at average CPI 2 on a 1 GHz CPU. Find execution time in milliseconds.`,2*(n+10),`Time = instructions × CPI / clock frequency. At 1 GHz, each million cycles takes 1 ms, giving ${2*(n+10)} ms.`);
 q('C / Data Structures','Arrays',`An int array starts at byte address ${1000+4*n}. Each int occupies 4 bytes. What is the byte address of A[${n+2}] (zero-based)?`,1000+4*n+4*(n+2),`Address = base + index × element size = ${1000+4*n} + ${n+2} × 4 = ${1000+4*n+4*(n+2)}.`);
 q('C / Data Structures','Trees',`A full binary tree (every internal node has two children) has ${n+3} internal nodes. How many leaves does it have?`,n+4,`For a full binary tree, leaves = internal nodes + 1 = ${n+4}.`);
 q('Algorithms','Loop counting',`How many times does count++ execute?\nfor (int i=1; i<=${n+5}; i++)\n  for (int j=1; j<=i; j++) count++;`,(n+5)*(n+6)/2,`The inner loop runs 1+2+…+${n+5} times. This is k(k+1)/2 = ${(n+5)*(n+6)/2}.`);
 q('Algorithms','Minimum spanning trees',`A connected undirected weighted graph has ${n+8} vertices. How many edges are in any minimum spanning tree?`,n+7,`Every spanning tree on V vertices has V−1 edges, so ${n+8}−1 = ${n+7}.`);
 q('Theory of Computation','Unary DFA',`Over alphabet {a}, what is the minimum number of DFA states for strings whose length is divisible by ${n+2}, including the empty string?`,n+2,`Track length modulo ${n+2}. All ${n+2} residues are reachable and distinguishable, so ${n+2} states are necessary and sufficient.`);
 q('Compiler Design','Lexical analysis',`A lexer reads ${n+2} repetitions of the statement x=x+1; (whitespace separates statements). How many tokens are produced in total?`,6*(n+2),`Each statement produces six tokens: identifier, =, identifier, +, number, ;. Total = 6 × ${n+2} = ${6*(n+2)}.`);
 q('Operating Systems','CPU scheduling',`Two processes arrive at t=0. P1 runs first under non-preemptive FCFS with burst ${n+3} ms; P2 has burst ${n+7} ms. What is the average waiting time in ms?`,(n+3)/2,`P1 waits 0; P2 waits ${n+3} ms. Average = (0+${n+3})/2 = ${(n+3)/2} ms.`);
 q('Operating Systems','Paging',`A process uses ${n+10} KiB of virtual memory. Page size is 4 KiB. How many pages are needed to cover this memory?`,Math.ceil((n+10)/4),`Round up memory/page size: ceil(${n+10}/4) = ${Math.ceil((n+10)/4)} pages.`);
 q('Databases','Relational algebra',`Relation R has ${n+3} tuples and relation S has ${n+6} tuples. How many tuples does R × S have?`,(n+3)*(n+6),`Each R tuple combines with each S tuple, so |R × S| = ${n+3} × ${n+6} = ${(n+3)*(n+6)}.`);
 q('Databases','Join cardinality',`Employee has ${n+20} rows. Each row has a non-null department_id referencing the unique primary key of Department. How many rows does an inner join on that key return?`,n+20,`Every employee matches exactly one department because of the non-null foreign key and unique referenced key. Thus ${n+20} rows.`);
 q('Computer Networks','Transmission delay',`A packet contains ${n+10} kB (1 kB = 1000 bytes). It is transmitted over a 8 Mbit/s link. Ignoring other delays, find transmission time in ms.`,n+10,`Time = bits/rate = (${n+10} × 1000 × 8)/(8 × 10^6) seconds = ${n+10} ms.`);
 return {id:n,questions:qs};
});
